-- RailBD production database support.
-- This migration is additive: it does not delete or seed your existing railway data.
-- Run it in Supabase SQL Editor before enabling passenger location verification.

create extension if not exists postgis;

create table if not exists public.train_routes (
  id bigint generated by default as identity primary key,
  train_number text not null,
  direction text not null,
  route geography(LineString, 4326) not null,
  source text default 'verified-railway-geometry',
  created_at timestamptz not null default now()
);

create index if not exists train_routes_geo_idx on public.train_routes using gist(route);
create index if not exists train_routes_number_idx on public.train_routes(train_number);
create index if not exists train_locations_number_created_idx on public.train_locations(train_number, created_at desc);
create index if not exists location_validations_session_created_idx on public.location_validations(session_id, created_at desc);

create or replace function public.validate_train_location(
  p_train_number text,
  p_lat double precision,
  p_lng double precision
)
returns table(distance_m double precision, route_fraction double precision)
language sql
stable
security definer
set search_path = public, extensions
as $$
  select
    st_distance(r.route, st_setsrid(st_point(p_lng, p_lat), 4326)::geography),
    st_linelocatepoint(r.route::geometry, st_setsrid(st_point(p_lng, p_lat), 4326))
  from public.train_routes r
  where r.train_number = p_train_number
  order by r.id desc
  limit 1;
$$;

-- Optional: add verified railway geometry here.
-- Do NOT use straight-line/demo coordinates for production claims.
-- Example:
-- insert into public.train_routes(train_number, direction, route, source)
-- values (
--   '753',
--   'Dhaka → Rajshahi',
--   st_geogfromtext('LINESTRING(90.4125 23.8103, 89.9720 24.4520, 89.0660 24.1130, 88.6070 24.3740)'),
--   'verified-railway-geometry'
-- );
